Contributing.md added
akshatnema/jobie pull request #12
Opened 2022-08-09 19:08 UTC by Priyansh61

**Description**

- ...
- ...
- ...

**Related issue(s)**

2022-08-09 19:19 UTC, Priyansh61 commented
Hey
I still need to figure out the .env config since i am having some trouble in loading the site locally with current configuration.

I have tried loading database with atlas, generated bearer token for twitter api but still all efforts are in vain and i end up getting a new error each time i use npm start in server side

I dont know what can i do there, so please it would be great if you can share how to set up the environment locally ?

2022-08-20 06:19 UTC, Priyansh61 commented
hey I have updated the contributing.md , do let me know if any changes needs to be made..

2022-08-20 15:34 UTC, akshatnema requested changes

2022-08-20 15:34 UTC, akshatnema commented on CONTRIBUTING.md
> +<h1>Contributing to JobiE</h1>
```suggestion
<h1>Contributing to JobIE</h1>
```

2022-08-20 15:34 UTC, akshatnema commented on CONTRIBUTING.md
> +<p>:wave: Hope you enjoy contributing to jobie :+1:</p>
```suggestion
<p>:wave: Hope you enjoy contributing to JobIE :+1:</p>
```

2022-08-20 15:34 UTC, akshatnema commented on CONTRIBUTING.md
> +```console
Don't merge the commands for ssh and HTTPS. Add them separately as:
Using SSH
```bash
  git clone git@github.com:<your_username>/jobie.git
```
OR
Using HTTPS:
```bash
git clone https://github.com/<your_username>/jobie.git
```

2022-08-20 15:34 UTC, akshatnema commented on CONTRIBUTING.md
> +<h3>Step 3:Build</h3>
Remove the installation of Nodejs installation from CONTRIBUTING.md file.

2022-08-20 15:34 UTC, akshatnema commented on CONTRIBUTING.md
> +   $ git rebase upstream/main
Remove this rebasing command.

2022-08-20 15:34 UTC, akshatnema commented on CONTRIBUTING.md
> +<h2>Testing</h2>
Presently, there are no tests available to check the linting or bugs in the changes. So, better you right now remove it and we will add this afterwards when tests will be added.

2022-08-21 07:41 UTC, Priyansh61 commented on CONTRIBUTING.md
> +   $ git rebase upstream/main
Removed the rebasing of branch

2022-08-21 07:42 UTC, Priyansh61 commented
All the necessary changes have been made, do let me know if anything is left?

2022-08-21 18:26 UTC, akshatnema commented on CONTRIBUTING.md
> +Your site will be hosted locally at: <b>http://localhost:8000/</b>
```suggestion
Your site will be hosted locally at: <b>http://localhost:3000/</b>
```

2022-08-24 15:27 UTC, akshatnema approved these changes
LGTM @Priyansh61 🥳

2022-08-24 15:28 UTC, merged

2022-08-25 14:54 UTC, Priyansh61 commented
Thanks.. Learnt a lot from you, will love to work more with you in future ☺️