Added Readme.md
akshatnema/jobie pull request #13
Opened 2022-08-20 06:40 UTC by thejaysharma

Made some changes to the readme.md

2022-08-20 15:45 UTC, akshatnema requested changes
It's a good contribution @thejaysharma. Well done mate. There are just some small changes and then we are ready to merge it. Here are these:
- Remove the `CONTRIBUTING.md` file from this PR as it is being created and updated in the other one.
- Change the directory of `assets` folder from the server to web and move the folder inside the web directory.

2022-08-20 15:45 UTC, akshatnema commented on CONTRIBUTING.md
> +
```suggestion
```

2022-08-20 19:18 UTC, thejaysharma commented on CONTRIBUTING.md
> +
Okay Sir, I'll do it.

2022-08-22 07:09 UTC, thejaysharma commented
Hello 
I have made the changes as per your review request, do let me know if any more changes need to be made ?? 😃

2022-08-24 15:36 UTC, akshatnema commented on README.md
> +Check Out  <a href="CONTRIBUTING.md">CONTRIBUTING.md</a>
```suggestion
Check Out  [CONTRIBUTING.md](/CONTRIBUTING.md)
```

2022-08-24 15:39 UTC, akshatnema approved these changes
LGTM @thejaysharma 🥳

2022-08-24 15:39 UTC, merged